# Copyright (c) 2026, AgriTheory and contributors
# For license information, please see license.txt

suppliers = [
	("Exceptional Grid", "Electricity", "Credit Card", 150.00),
	("Liu & Loewen Accountants LLP", "Accounting Services", "Check", 750.00),
	("Mare Digitalis", "Cloud Services", "Credit Card", 200.00),
	("AgriTheory", "ERPNext Consulting", "Check", 1000.00),
	("HIJ Telecom, Inc", "Internet Services", "Check", 150.00),
	("Sphere Cellular", "Phone Services", "Credit Card", 250.00),
	("Cooperative Ag Finance", "Financial Services", "Bank Draft", 5000.00),
	("Premier Equipment Leasing", "Equipment Lease", "Check", 5000.00),
	("North County Grain Cooperative", "Grain Supply", "Bank Draft", 5000.00),
]

tax_authority = [
	("Local Tax Authority", "Payroll Taxes", "Check", 0.00),
]

customers = [
	("Chelsea Fruit Wholesale", 10000),
]

# Customer credit limit example — test data only, not installed with the app.
customer_credit_limit_reapproval_condition = (
	"{{ doc.credit_limits and flt(doc.credit_limits[0].credit_limit) "
	"!= flt(doc.last_approved_credit_limit or 0) }}"
)

customer_custom_fields = [
	{
		"dt": "Customer",
		"fieldname": "workflow_state",
		"fieldtype": "Link",
		"label": "Workflow State",
		"options": "Workflow State",
		"insert_after": "customer_name",
		"hidden": 1,
		"read_only": 1,
		"no_copy": 1,
	},
	{
		"dt": "Customer",
		"fieldname": "last_approved_credit_limit",
		"fieldtype": "Currency",
		"label": "Last Approved Credit Limit",
		"insert_after": "workflow_state",
		"read_only": 1,
	},
]

customer_credit_limit_workflow = {
	"name": "Customer Credit Limit",
	"docstatus": 0,
	"idx": 0,
	"workflow_name": "Customer Credit Limit",
	"document_type": "Customer",
	"is_active": 1,
	"override_status": 0,
	"send_email_alert": 0,
	"workflow_state_field": "workflow_state",
	"approval_state": "Pending Approval",
	"reapproval_condition": customer_credit_limit_reapproval_condition,
	"states": [
		{
			"idx": 1,
			"state": "Draft",
			"doc_status": "0",
			"is_optional_state": 0,
			"avoid_status_override": 0,
			"allow_edit": "All",
		},
		{
			"idx": 2,
			"state": "Pending Approval",
			"doc_status": "0",
			"is_optional_state": 0,
			"avoid_status_override": 0,
			"allow_edit": "All",
			"style": "Warning",
		},
		{
			"idx": 3,
			"state": "Approved",
			"doc_status": "0",
			"is_optional_state": 0,
			"avoid_status_override": 0,
			"allow_edit": "All",
			"is_approved_state_for_non_submittable_document": 1,
			"update_field": "last_approved_credit_limit",
			"update_value": "{{ doc.credit_limits[0].credit_limit if doc.credit_limits else 0 }}",
		},
	],
	"transitions": [
		{
			"idx": 1,
			"state": "Draft",
			"action": "Send for Approval",
			"next_state": "Pending Approval",
			"allowed": "All",
			"allow_self_approval": 1,
		},
		{
			"idx": 2,
			"state": "Pending Approval",
			"action": "Approve",
			"next_state": "Approved",
			"allowed": "All",
			"allow_self_approval": 1,
		},
		{
			"idx": 3,
			"state": "Pending Approval",
			"action": "Reject",
			"next_state": "Draft",
			"allowed": "All",
			"allow_self_approval": 1,
		},
	],
}

customer_credit_limit_approval_rule = {
	"approval_doctype": "Customer",
	"approval_role": "Sales Manager",
	"condition": "{{ doc.workflow_state == 'Pending Approval' }}",
	"enabled": 1,
	"message": "Customer credit limit requires your approval",
}

document_approval_rules = [
	{
		"approval_doctype": "Purchase Order",
		"approval_role": "Accounts Manager",
		"primary_assignee": "mbritt@cfc.co",
		"condition": "{{ doc.grand_total > 1000 }}",
		"enabled": 1,
	},
	{
		"approval_doctype": "Purchase Invoice",
		"approval_role": "Accounts Manager",
		"primary_assignee": "mbritt@cfc.co",
		"condition": "{{ doc.grand_total > 1000 }}",
		"enabled": 1,
	},
	{
		"approval_doctype": "Purchase Order",
		"approval_role": "Stock Manager",
		"primary_assignee": "arivers@cfc.co",
		"condition": "{{ doc.grand_total > 200 and doc.grand_total < 500 }}",
		"enabled": 1,
	},
	{
		"approval_doctype": "Purchase Invoice",
		"approval_role": "Stock Manager",
		"primary_assignee": "arivers@cfc.co",
		"condition": "{{ doc.grand_total > 200 and doc.grand_total < 500 }}",
		"enabled": 1,
	},
	{
		"approval_doctype": "Purchase Order",
		"approval_role": "Sales Manager",
		"primary_assignee": "mmckay@cfc.co",
		"condition": "{{ doc.grand_total > 500 and doc.grand_total < 1000 }}",
		"enabled": 1,
	},
	{
		"approval_doctype": "Purchase Invoice",
		"approval_role": "Sales Manager",
		"primary_assignee": "mmckay@cfc.co",
		"condition": "{{ doc.grand_total > 500 and doc.grand_total < 1000 }}",
		"enabled": 1,
	},
	customer_credit_limit_approval_rule | {"primary_assignee": "mmckay@cfc.co"},
]


workflows = [
	{
		"name": "Purchase Order",
		"docstatus": 0,
		"idx": 0,
		"workflow_name": "Purchase Order",
		"document_type": "Purchase Order",
		"is_active": 1,
		"override_status": 0,
		"send_email_alert": 0,
		"workflow_state_field": "workflow_state",
		"approval_state": "Pending Approval",
		"approval_action": "Approve",
		"states": [
			{
				"idx": 1,
				"state": "Draft",
				"doc_status": "0",
				"is_optional_state": 0,
				"avoid_status_override": 0,
				"allow_edit": "All",
			},
			{
				"idx": 2,
				"state": "Pending Approval",
				"doc_status": "0",
				"is_optional_state": 0,
				"avoid_status_override": 0,
				"allow_edit": "All",
				"style": "Warning",
			},
			{
				"name": "lkeo0p1tjq",
				"owner": "Administrator",
				"creation": "2024-07-08 16:12:31.183859",
				"modified": "2024-07-08 16:12:31.183859",
				"modified_by": "Administrator",
				"docstatus": 0,
				"idx": 3,
				"state": "Approved",
				"doc_status": "1",
				"is_optional_state": 0,
				"avoid_status_override": 0,
				"allow_edit": "All",
			},
			{
				"idx": 4,
				"state": "Cancelled",
				"doc_status": "2",
				"is_optional_state": 0,
				"avoid_status_override": 0,
				"allow_edit": "All",
				"style": "Inverse",
			},
		],
		"transitions": [
			{
				"idx": 1,
				"state": "Draft",
				"action": "Save",
				"next_state": "Draft",
				"allowed": "All",
				"allow_self_approval": 1,
			},
			{
				"idx": 2,
				"state": "Draft",
				"action": "Send for Approval",
				"next_state": "Pending Approval",
				"allowed": "All",
				"allow_self_approval": 1,
			},
			{
				"idx": 3,
				"state": "Pending Approval",
				"action": "Approve",
				"next_state": "Approved",
				"allowed": "All",
				"allow_self_approval": 1,
			},
			{
				"idx": 4,
				"state": "Pending Approval",
				"action": "Reject",
				"next_state": "Draft",
				"allowed": "All",
				"allow_self_approval": 1,
			},
			{
				"idx": 5,
				"state": "Approved",
				"action": "Cancel",
				"next_state": "Cancelled",
				"allowed": "All",
				"allow_self_approval": 1,
			},
		],
	},
	customer_credit_limit_workflow,
]


employees = [
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1977-03-06",
		"date_of_joining": "2019-04-12",
		"employee_name": "Arden Rivers",
		"employment_type": "Full-time",
		"first_name": "Arden",
		"gender": "Male",
		"last_name": "Rivers",
		"status": "Active",
		"tin": "004-48-0067",
		"roles": ["Stock Manager", "Item Manager"],
		"designation": "Associate",
		"reports_to": "Darnell Benton",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1984-04-23",
		"date_of_joining": "2019-07-04",
		"employee_name": "Minh McKay",
		"employment_type": "Full-time",
		"first_name": "Minh",
		"gender": "Female",
		"last_name": "McKay",
		"status": "Active",
		"tin": "002-27-6877",
		"roles": ["Sales User", "Sales Manager", "Sales Master Manager"],
		"designation": "Associate",
		"reports_to": "Darnell Benton",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1980-07-06",
		"date_of_joining": "2019-07-28",
		"employee_name": "Morgan Britt",
		"employment_type": "Full-time",
		"first_name": "Morgan",
		"gender": "Female",
		"last_name": "Britt",
		"status": "Active",
		"tin": "009-00-2414",
		"roles": [
			"Accounts Manager",
			"Accounts User",
			"Purchase User",
			"Purchase Manager",
			"Purchase Master Manager",
		],
		"designation": "Associate",
		"reports_to": "Darnell Benton",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1984-06-29",
		"date_of_joining": "2020-01-12",
		"employee_name": "Marcellus Reeves",
		"employment_type": "Full-time",
		"first_name": "Marcellus",
		"gender": "Male",
		"last_name": "Reeves",
		"status": "Active",
		"tin": "003-47-4528",
		"roles": ["Stock User"],
		"designation": "Associate",
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1998-04-22",
		"date_of_joining": "2020-03-20",
		"designation": "Associate",
		"employee_name": "Assunta Jimenez",
		"employment_type": "Full-time",
		"first_name": "Assunta",
		"gender": "Female",
		"last_name": "Jimenez",
		"status": "Active",
		"tin": "002-90-1544",
		"roles": ["Stock User"],
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1979-06-18",
		"date_of_joining": "2020-09-08",
		"designation": "Associate",
		"employee_name": "Alton Sears",
		"employment_type": "Full-time",
		"first_name": "Alton",
		"gender": "Male",
		"last_name": "Sears",
		"status": "Active",
		"tin": "000-52-4669",
		"roles": ["Stock User"],
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1991-08-17",
		"date_of_joining": "2020-11-01",
		"designation": "Associate",
		"employee_name": "Eli Serrano",
		"employment_type": "Full-time",
		"first_name": "Eli",
		"gender": "Male",
		"last_name": "Serrano",
		"status": "Active",
		"tin": "000-49-0783",
		"roles": ["Stock User"],
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1997-09-13",
		"date_of_joining": "2021-02-22",
		"employee_name": "Sumiko Kim",
		"employment_type": "Full-time",
		"first_name": "Sumiko",
		"gender": "Female",
		"last_name": "Kim",
		"status": "Active",
		"tin": "004-82-6553",
		"roles": ["Sales User"],
		"designation": "Associate",
		"reports_to": "Minh McKay",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1979-11-08",
		"date_of_joining": "2021-03-11",
		"employee_name": "Riley Sutton",
		"employment_type": "Full-time",
		"first_name": "Riley",
		"gender": "Other",
		"last_name": "Sutton",
		"status": "Active",
		"tin": "002-23-2941",
		"roles": ["Sales User"],
		"designation": "Associate",
		"reports_to": "Minh McKay",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1987-07-10",
		"date_of_joining": "2021-06-21",
		"employee_name": "Andrea Buchanan",
		"employment_type": "Full-time",
		"first_name": "Andrea",
		"gender": "Female",
		"last_name": "Buchanan",
		"status": "Active",
		"tin": "007-91-4605",
		"roles": ["Stock User"],
		"designation": "Associate",
		"reports_to": "Arden Rivers",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1994-07-27",
		"date_of_joining": "2021-06-24",
		"employee_name": "Rashad Bruce",
		"employment_type": "Full-time",
		"first_name": "Rashad",
		"gender": "Male",
		"last_name": "Bruce",
		"status": "Active",
		"tin": "004-84-1349",
		"roles": ["Sales User"],
		"designation": "Associate",
		"reports_to": "Minh McKay",
	},
	{
		"company": "Chelsea Fruit Co",
		"date_of_birth": "1999-10-04",
		"date_of_joining": "2021-08-01",
		"employee_name": "Darnell Benton",
		"employment_type": "Full-time",
		"first_name": "Darnell",
		"gender": "Female",
		"last_name": "Benton",
		"status": "Active",
		"tin": "006-77-6510",
		"designation": "Associate",
		"roles": [
			"Item Manager",
			"Sales User",
			"Sales Manager",
			"Sales Master Manager",
			"Accounts Manager",
			"Accounts User",
			"HR Manager",
			"HR User",
			"Stock User",
			"Sales User",
		],
	},
]
